In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.2.2'

In [4]:
df = pd.read_csv('/Users/amol/code/learnings/DE/tmp/yellow_tripdata_2019-01.csv', nrows = 100)

In [5]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2019-01-01 00:46:40,2019-01-01 00:53:20,1,1.50,1,N,151,239,1,7.0,0.5,0.5,1.65,0.0,0.3,9.95,NaN
1,1,2019-01-01 00:59:47,2019-01-01 01:18:59,1,2.60,1,N,239,246,1,14.0,0.5,0.5,1.00,0.0,0.3,16.30,NaN
2,2,2018-12-21 13:48:30,2018-12-21 13:52:40,3,0.00,1,N,236,236,1,4.5,0.5,0.5,0.00,0.0,0.3,5.80,NaN
3,2,2018-11-28 15:52:25,2018-11-28 15:55:45,5,0.00,1,N,193,193,2,3.5,0.5,0.5,0.00,0.0,0.3,7.55,NaN
4,2,2018-11-28 15:56:57,2018-11-28 15:58:33,5,0.00,2,N,193,193,2,52.0,0.0,0.5,0.00,0.0,0.3,55.55,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,2019-01-01 00:02:06,2019-01-01 00:10:19,2,2.57,1,N,45,97,1,9.5,0.5,0.5,2.16,0.0,0.3,12.96,NaN
96,2,2019-01-01 00:24:57,2019-01-01 00:35:42,2,2.44,1,N,144,256,2,10.5,0.5,0.5,0.00,0.0,0.3,11.80,NaN
97,2,2019-01-01 00:46:09,2019-01-01 01:06:46,1,4.18,1,N,79,263,1,16.0,0.5,0.5,3.46,0.0,0.3,20.76,NaN
98,1,2019-01-01 00:16:07,2019-01-01 00:19:41,1,1.00,1,N,140,233,1,5.0,0.5,0.5,1.00,0.0,0.3,7.30,NaN
99,1,2019-01-01 00:23:47,2019-01-01 00:39:41,1,3.90,1,N,229,238,1,14.5,0.5,0.5,4.70,0.0,0.3,20.50,NaN

In [7]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

In [8]:
from sqlalchemy import create_engine

In [21]:
engine = create_engine('postgresql://data:data@host.docker.internal:5432/ny_taxi', )

In [30]:
print(pd.io.sql.get_schema(df, name = 'yellow_taxi_data', con=engine))

CREATE TABLE yellow_taxi_data (
	"VendorID" BIGINT,
	tpep_pickup_datetime TIMESTAMP WITHOUT TIME ZONE,
	tpep_dropoff_datetime TIMESTAMP WITHOUT TIME ZONE,
	passenger_count BIGINT,
	trip_distance FLOAT(53),
	"RatecodeID" BIGINT,
	store_and_fwd_flag TEXT,
	"PULocationID" BIGINT,
	"DOLocationID" BIGINT,
	payment_type BIGINT,
	fare_amount FLOAT(53),
	extra FLOAT(53),
	mta_tax FLOAT(53),
	tip_amount FLOAT(53),
	tolls_amount FLOAT(53),
	improvement_surcharge FLOAT(53),
	total_amount FLOAT(53),
	congestion_surcharge FLOAT(53)
)

In [22]:
dataframe_iterator = pd.read_csv('/Users/amol/code/learnings/DE/tmp/yellow_tripdata_2019-01.csv', iterator= True, chunksize=100000)

In [23]:
dataframe = next(dataframe_iterator)

In [24]:
len(dataframe)

100000

In [25]:
dataframe.tpep_pickup_datetime = pd.to_datetime(dataframe.tpep_pickup_datetime)
dataframe.tpep_dropoff_datetime = pd.to_datetime(dataframe.tpep_dropoff_datetime)

In [26]:
dataframe.head(5)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2019-01-01 00:46:40,2019-01-01 00:53:20,1,1.5,1,N,151,239,1,7.0,0.5,0.5,1.65,0.0,0.3,9.95,NaN
1,1,2019-01-01 00:59:47,2019-01-01 01:18:59,1,2.6,1,N,239,246,1,14.0,0.5,0.5,1.00,0.0,0.3,16.30,NaN
2,2,2018-12-21 13:48:30,2018-12-21 13:52:40,3,0.0,1,N,236,236,1,4.5,0.5,0.5,0.00,0.0,0.3,5.80,NaN
3,2,2018-11-28 15:52:25,2018-11-28 15:55:45,5,0.0,1,N,193,193,2,3.5,0.5,0.5,0.00,0.0,0.3,7.55,NaN
4,2,2018-11-28 15:56:57,2018-11-28 15:58:33,5,0.0,2,N,193,193,2,52.0,0.0,0.5,0.00,0.0,0.3,55.55,NaN

In [27]:
dataframe.head(n=0).to_sql(name='yellow_taxi_data', con = engine, if_exists='replace')

OperationalError: (psycopg2.OperationalError) could not translate host name "host.docker.internal" to address: nodename nor servname provided, or not known

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [38]:
%time dataframe.to_sql(name='yellow_taxi_data', con = engine, if_exists='append')

CPU times: user 6.91 s, sys: 197 ms, total: 7.11 s
Wall time: 17.5 s

1000